// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using WindowsFormsApp1;
//
//    var erkezes = Erkezes.FromJson(jsonString);

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Erkezes
    {
        [JsonProperty("gyumolcsid")]
        public long Gyumolcsid { get; set; }

        [JsonProperty("mennyiseg")]
        public long Mennyiseg { get; set; }

        [JsonProperty("egysegar")]
        public string Egysegar { get; set; }

        [JsonProperty("erkezett")]
        public DateTimeOffset Erkezett { get; set; }
    }

    public partial class Erkezes
    {
        public static List<Erkezes> FromJson(string json) => JsonConvert.DeserializeObject<List<Erkezes>>(json, WindowsFormsApp1.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this List<Erkezes> self) => JsonConvert.SerializeObject(self, WindowsFormsApp1.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
