// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using WindowsFormsApp1;
//
//    var gyumolcs = Gyumolcs.FromJson(jsonString);

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Gyumolcs
    {
        [JsonProperty("gyumolcsid")]
        public long Gyumolcsid { get; set; }

        [JsonProperty("nev")]
        public string Nev { get; set; }

        [JsonProperty("megjegyzes")]
        public string Megjegyzes { get; set; }

        [JsonProperty("nev_eng")]
        public string NevEng { get; set; }

        [JsonProperty("alt_szoveg")]
        public string AltSzoveg { get; set; }

        [JsonProperty("src")]
        public string Src { get; set; }
    }

    public partial class Gyumolcs
    {
        public static List<Gyumolcs> FromJson(string json) => JsonConvert.DeserializeObject<List<Gyumolcs>>(json, WindowsFormsApp1.Converter.Settings);
    }

    //public static class Serialize
    //{
    //    public static string ToJson(this List<Gyumolcs> self) => JsonConvert.SerializeObject(self, WindowsFormsApp1.Converter.Settings);
    //}

    //internal static class Converter
    //{
    //    public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
    //    {
    //        MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
    //        DateParseHandling = DateParseHandling.None,
    //        Converters =
    //        {
    //            new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
    //        },
    //    };
    //}
}
